[package]
name = "countdown-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datetime = "0.5.2"
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
